apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "petclinic-chart.fullname" . }}-db-config
  labels:
    {{- include "petclinic-chart.dbLabels" . | nindent 4 }}
data:
  DB_HOST: {{ include "petclinic-chart.fullname" . }}-db-service
  DB_PORT: "{{ .Values.database.port }}"
  DB_NAME: {{ .Values.database.name }}