apiVersion: v1
kind: Secret
metadata:
  name: {{ include "petclinic-chart.fullname" . }}-db-secret
  labels:
    {{- include "petclinic-chart.dbLabels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}