
apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic-chart.fullname" . }}-db-service
  labels:
    {{- include "petclinic-chart.dbLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "petclinic-chart.dbSelectorLabels" . | nindent 4 }}
