fullnameOverride: petclinic

image:
  repository: spring-petclinic
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

database:
  image: postgres:15
  port: 5432
  name: petclinic
  username: petclinic
  password: petclinic
  persistence:
    enabled: true
    size: 1Gi
  existingSecret: ""
  usePostgres: true

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: petclinic.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}